---
- name: Get selinux state
  command: getenforce
  register: getenforce

- name: Manage selinux
  when: getenforce.stdout == "Enforcing"
  block:
    - name: Allow Apache to listen on tcp port {{ wapi_port }}
      seport:
        ports: "{{ wapi_port }}"
        proto: tcp
        setype: http_port_t
        state: present

- name: Deploy httpd config
  become: true
  become_user: root
  block:
    - name: Deploy apache configuration
      template:
        src: httpd.conf
        dest: /etc/httpd/conf.d/wapi.conf

    - name: Manage firewalld
      firewalld:
        port: "{{ wapi_port }}/tcp"
        permanent: yes
        state: enabled
        immediate: yes

    - name: Reload apache config
      systemd:
        name: httpd
        state: reloaded
        enabled: yes
...