---
user: {{ wapi_user }}
inventories:
  - /home/{{ wapi_user }}/{{ git_name }}/test/inventories/hosts
runs_dir: /home/{{ wapi_user }}/wapi_runs
ansible_cmdline:
  playbook: ansible-playbook
ansible_private_key:
  - "/home/{{ wapi_user }}/.ssh/wapi_rsa"
  - "/home/{{ wapi_user }}/ansible-ws/tests/data/agent/wapi_rsa"
  - "fake_key"
...