---
user: {{ wapi_user }}
inventories:
  - /home/{{ wapi_user }}/{{ git_name }}/test/inventories/hosts
runs_dir: /home/{{ wapi_user }}/wapi_runs
ansible_cmdline:
  playbook: ansible-playbook-3
ansible_private_key:
  - "/home/{{ wapi_user }}/.ssh/ansible-ws"
  - "/home/{{ wapi_user }}/ansible-ws/tests/data/agent/key1"
  - "/home/{{ wapi_user }}/ansible-ws/tests/data/agent/key2"
  - "fake_key"
...