#
# {{ ansible_managed }}
#
---
user: {{ wapi_user }}
inventories:
  - /home/{{ wapi_user }}/{{ git_name }}/test/inventories
run_options: -v --diff
runs_dir: /home/{{ wapi_user }}/ansible-ws@working/runs
ansible_cmdline:
  playbook: ansible-playbook
ansible_private_key:
  - "/home/{{ wapi_user }}/.ssh/ansible-ws"
#   - "/home/{{ wapi_user }}/ansible-ws/tests/data/agent/key1"
#   - "/home/{{ wapi_user }}/ansible-ws/tests/data/agent/key2"
#   - "fake_key"
...