---
- hosts: localhost
  gather_facts: true
  become: yes
  become_user: root
  vars:
    git_version: master
    git_clone: true
    git_repos:
      - liftree
      - ansible-ws
      - wapi
  tasks:
    - name: Remove existing WAPI liftree config.
      file:
        path: /etc/liftree/conf.d/50-wapi.conf
        state: absent
    - name: Clone repo
      git:
        repo: https://github.com/vengaar/{{ repo_name }}.git
        dest: /tmp/{{ repo_name }}
        version: "{{ git_version }}"
        force: yes
      loop: "{{ git_repos }}"
      loop_control:
        loop_var: repo_name

    - name: Setup
      include_role:
        name: /tmp/{{ repo_name }}/setup/playbooks/roles/setup
      vars:
        wsgi_user: "wapi"
        version: "{{ git_version }}"
      loop: "{{ git_repos }}"
      loop_control:
        loop_var: repo_name
...