---
- hosts: localhost
  gather_facts: true
  become: yes
  become_user: root
  vars:
    git_version: master
    git_clone: true
    git_repos:
      - liftree
      - ansible-ws
      - wapi
  tasks:

    - name: Ensure pre-requiste
      assert:
        that:
          - ansible_distribution == "Fedora"
          - ansible_distribution_major_version|int >= 28  

    - name: Clone repo
      git:
        repo: https://github.com/vengaar/{{ git_repo }}.git
        dest: /tmp/{{ git_repo }}
        version: "{{ git_version }}"
      loop: "{{ git_repos }}"
      loop_control:
        loop_var: git_repo

    - name: Setup
      include_role:
        name: /tmp/{{ git_repo }}/setup/playbooks/roles/setup
      vars:
        wsgi_user: "wapi"
        version: "{{ git_version }}"
      loop: "{{ git_repos }}"
      loop_control:
        loop_var: git_repo
...