---
- hosts: localhost
  gather_facts: true
  become: yes
  become_user: root
  vars:
    wsgi_user: "wapi"
    version_liftree: "{{ version|default('HEAD') }}"
    version_ansible_ws: "{{ version|default('HEAD') }}"
    version_wapi: "{{ version|default('HEAD') }}"
    git_clone: true
    git_repos:
      - name: liftree
        version: "{{ version_liftree }}"
      - name: ansible-ws
        version: "{{ version_ansible_ws }}"
      - name: wapi
        version: "{{ version_wapi }}"
  tasks:
    - name: Clone repo
      git:
        repo: https://github.com/vengaar/{{ git_app.name }}.git
        dest: /tmp/{{ git_app.name }}
        version: "{{ git_app.version }}"
        force: yes
      loop: "{{ git_repos }}"
      loop_control:
        loop_var: git_app

    - name: Setup liftree
      include_role:
        name: /tmp/liftree/setup/playbooks/roles/setup
      vars:
        git_version: "{{ version_liftree }}"

    - name: Setup ansible-ws
      include_role:
        name: /tmp/ansible-ws/setup/playbooks/roles/setup
      vars:
        git_version: "{{ version_ansible_ws }}"

    - name: Setup wapi
      include_role:
        name: /tmp/wapi/setup/playbooks/roles/setup
      vars:
        git_version: "{{ version_wapi }}"
...