---
- hosts: localhost
  gather_facts: true
  become: yes
  become_user: root
  vars:
    git_clone: true
    git_repos:
      - liftree
      - ansible-ws
      - wapi
  tasks:

    - name: Ensure pre-requiste
      assert:
        that:
          - ansible_distribution == "Fedora"
          - ansible_distribution_major_version|int >= 28  

    - name: Clone repo
      git:
        repo: https://github.com/vengaar/{{ item }}.git
        dest: /tmp/{{ item }}
      loop: "{{ git_repos }}"

    - name: Setup
      include_role:
        name: /tmp/{{ item }}/setup/playbooks/roles/setup
        wsgi_user: "wapi"
      loop: "{{ git_repos }}"

...