---
- hosts: localhost
  gather_facts: true
  become: yes
  become_user: root
  vars:
    git_clone: true
    git_repos:
      - name: liftree
        version: "{{ git_version|default('HEAD') }}"
      - name: ansible-ws
        version: "{{ git_version|default('HEAD') }}"
      - name: wapi
        version: "{{ git_version|default('HEAD') }}"
  tasks:
    - name: Clone repo
      git:
        repo: https://github.com/vengaar/{{ git_app.name }}.git
        dest: /tmp/{{ git_app.name }}
        version: "{{ git_app.version }}"
        force: yes
      loop: "{{ git_repos }}"
      loop_control:
        loop_var: git_app

    - name: Setup
      include_role:
        name: /tmp/{{ git_app.name }}/setup/playbooks/roles/setup
      vars:
        wsgi_user: "wapi"
        git_version: "{{ git_app.version }}"
      loop: "{{ git_repos }}"
      loop_control:
        loop_var: git_app
...