---

- hosts: localhost
  gather_facts: false
  become: yes
  become_user: root  
  tasks:
  
    - name: Deploy wapi liftree config
      copy:
        dest: /etc/liftree/conf.d/50-wapi.conf
        content: |
          ---
          name: /home/liftree/wapi/liftree
          ...

    - name: Create configuration directory
      file:
        path: /etc/wapi
        state: directory

    - name: Deploy wapi config
      copy:
        dest: /etc/wapi/wapi.yaml
        content: |
          ---
          inventories:
            - /home/liftree/wapi/test/inventories/hosts
          ...

...